stages:
  - build

## Add variables, such as SERVER_IP,GATEWAY_IP etc, to Gitlab CI variables ##

create_test_centos7:
  stage: build
  tags:
      - packer
  image: alpine:3.12.0
  before_script:
    - echo "Fetching packer 1.5.5"
    - wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    - unzip packer_1.5.5_linux_amd64.zip
    - chmod +x packer
  script:
    - sed -i "s,__SERVER_IP__,$SERVER_IP," ks.cfg
    - sed -i "s,__GATEWAY_IP__,$GATEWAY_IP," ks.cfg
    - sed -i "s,__DNS_SERVER_IP__,$DNS_SERVER_IP," ks.cfg
    - sed -i "s,__PROVISIONING_USERNAME__,$PROVISIONING_USERNAME," ks.cfg
    - sed -i "s,__IMAGE_BUILDER__,$GITLAB_USER_LOGIN," ks.cfg
    - sed -i "s,__TEMPLATE_VERSION__,$CI_PIPELINE_ID," ks.cfg

    - sed -i "s,__VCENTER_SERVER__,$TEST_VCENTER_SERVER," variables.json
    - sed -i "s,__VCENTER_USERNAME__,$VCENTER_USERNAME," variables.json
    - sed -i "s,__VCENTER_PASSWORD__,$VCENTER_PASSWORD," variables.json
    - sed -i "s,__DATACENTER__,$TEST_DATACENTER," variables.json
    - sed -i "s,__DATASTORE__,$TEST_DATASTORE," variables.json
    - sed -i "s,__FOLDER__,$FOLDER," variables.json
    - sed -i "s,__CLUSTER__,$TEST_CLUSTER," variables.json
    - sed -i "s,__NETWORK__,$TEST_NETWORK," variables.json
    - sed -i "s,__PROVISIONING_USERNAME__,$PROVISIONING_USERNAME," variables.json
    - sed -i "s,__PROVISIONING_PASSWORD_PLAIN__,$PROVISIONING_PASSWORD_PLAIN," variables.json
    - sed -i "s,__SERVER_IP__,$SERVER_IP," variables.json
    - sed -i "s,__ISO_PATH__,$TEST_ISO_PATH," variables.json
    - sed -i "s,__ISO_CHECKSUM__,$ISO_CHECKSUM," variables.json

    - ./packer build -force -var-file=variables.json centos7.json
  only:
    - develop

create_prd_centos7:
  stage: build
  tags:
      - packer
  image: alpine:3.12.0
  before_script:
    - echo "Fetching packer 1.5.5"
    - wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
    - unzip packer_1.5.5_linux_amd64.zip
    - chmod +x packer
  script:
    - sed -i "s,__SERVER_IP__,$SERVER_IP," ks.cfg
    - sed -i "s,__GATEWAY_IP__,$GATEWAY_IP," ks.cfg
    - sed -i "s,__DNS_SERVER_IP__,$DNS_SERVER_IP," ks.cfg
    - sed -i "s,__PROVISIONING_USERNAME__,$PROVISIONING_USERNAME," ks.cfg
    - sed -i "s,__IMAGE_BUILDER__,$GITLAB_USER_LOGIN," ks.cfg
    - sed -i "s,__TEMPLATE_VERSION__,$CI_PIPELINE_ID," ks.cfg

    - sed -i "s,__VCENTER_SERVER__,$PROD_VCENTER_SERVER," variables.json
    - sed -i "s,__VCENTER_USERNAME__,$VCENTER_USERNAME," variables.json
    - sed -i "s,__VCENTER_PASSWORD__,$VCENTER_PASSWORD," variables.json
    - sed -i "s,__DATACENTER__,$PROD_DATACENTER," variables.json
    - sed -i "s,__DATASTORE__,$PROD_DATASTORE," variables.json
    - sed -i "s,__FOLDER__,$FOLDER," variables.json
    - sed -i "s,__CLUSTER__,$PROD_CLUSTER," variables.json
    - sed -i "s,__NETWORK__,$PROD_NETWORK," variables.json
    - sed -i "s,__PROVISIONING_USERNAME__,$PROVISIONING_USERNAME," variables.json
    - sed -i "s,__PROVISIONING_PASSWORD_PLAIN__,$PROVISIONING_PASSWORD_PLAIN," variables.json
    - sed -i "s,__SERVER_IP__,$SERVER_IP," variables.json
    - sed -i "s,__ISO_PATH__,$PROD_ISO_PATH," variables.json
    - sed -i "s,__ISO_CHECKSUM__,$ISO_CHECKSUM," variables.json

    - ./packer build -force -var-file=variables.json centos7.json
  only:
    - master